
# This file is automatically generated, you probably don't want to edit this

areachartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "areachartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = NULL,
            timeVar = NULL,
            timeVar1 = NULL,
            vars = NULL,
            var = NULL,
            group = NULL,
            showLine = TRUE,
            position = "stack",
            colorPalette = "jmv",
            isDate = FALSE,
            dateFormat = "auto",
            displayFormat = "%Y-%m-%d",
            dateBreak = "1 month",
            rotateLabels = FALSE,
            plotWidth = 0,
            plotHeight = 0,
            lineWidth = 0.5,
            ylabel = NULL, ...) {

            super$initialize(
                package="vijPlots",
                name="areachart",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "oneVariable",
                    "severalVariables"))
            private$..timeVar <- jmvcore::OptionVariable$new(
                "timeVar",
                timeVar,
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..timeVar1 <- jmvcore::OptionVariable$new(
                "timeVar1",
                timeVar1,
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..showLine <- jmvcore::OptionBool$new(
                "showLine",
                showLine,
                default=TRUE)
            private$..position <- jmvcore::OptionList$new(
                "position",
                position,
                options=list(
                    "stack",
                    "fill",
                    "identity"),
                default="stack")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"),
                default="jmv")
            private$..isDate <- jmvcore::OptionBool$new(
                "isDate",
                isDate,
                default=FALSE)
            private$..dateFormat <- jmvcore::OptionList$new(
                "dateFormat",
                dateFormat,
                options=list(
                    "auto",
                    "iso",
                    "us",
                    "eu"),
                default="auto")
            private$..displayFormat <- jmvcore::OptionList$new(
                "displayFormat",
                displayFormat,
                options=list(
                    "%Y-%m-%d",
                    "%m/%d/%y",
                    "%d/%m/%y",
                    "%Y %B %e ",
                    "%e %B %Y",
                    "%B %Y",
                    "%Y %B",
                    "%b",
                    "%B",
                    "%Y"),
                default="%Y-%m-%d")
            private$..dateBreak <- jmvcore::OptionList$new(
                "dateBreak",
                dateBreak,
                options=list(
                    "1 day",
                    "1 week",
                    "2 week",
                    "1 month",
                    "3 month",
                    "6 month",
                    "1 year",
                    "10 year"),
                default="1 month")
            private$..rotateLabels <- jmvcore::OptionBool$new(
                "rotateLabels",
                rotateLabels,
                default=FALSE)
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1000,
                default=0)
            private$..lineWidth <- jmvcore::OptionNumber$new(
                "lineWidth",
                lineWidth,
                min=0.1,
                max=10,
                default=0.5)
            private$..ylabel <- jmvcore::OptionString$new(
                "ylabel",
                ylabel)

            self$.addOption(private$..mode)
            self$.addOption(private$..timeVar)
            self$.addOption(private$..timeVar1)
            self$.addOption(private$..vars)
            self$.addOption(private$..var)
            self$.addOption(private$..group)
            self$.addOption(private$..showLine)
            self$.addOption(private$..position)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..isDate)
            self$.addOption(private$..dateFormat)
            self$.addOption(private$..displayFormat)
            self$.addOption(private$..dateBreak)
            self$.addOption(private$..rotateLabels)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..lineWidth)
            self$.addOption(private$..ylabel)
        }),
    active = list(
        mode = function() private$..mode$value,
        timeVar = function() private$..timeVar$value,
        timeVar1 = function() private$..timeVar1$value,
        vars = function() private$..vars$value,
        var = function() private$..var$value,
        group = function() private$..group$value,
        showLine = function() private$..showLine$value,
        position = function() private$..position$value,
        colorPalette = function() private$..colorPalette$value,
        isDate = function() private$..isDate$value,
        dateFormat = function() private$..dateFormat$value,
        displayFormat = function() private$..displayFormat$value,
        dateBreak = function() private$..dateBreak$value,
        rotateLabels = function() private$..rotateLabels$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        lineWidth = function() private$..lineWidth$value,
        ylabel = function() private$..ylabel$value),
    private = list(
        ..mode = NA,
        ..timeVar = NA,
        ..timeVar1 = NA,
        ..vars = NA,
        ..var = NA,
        ..group = NA,
        ..showLine = NA,
        ..position = NA,
        ..colorPalette = NA,
        ..isDate = NA,
        ..dateFormat = NA,
        ..displayFormat = NA,
        ..dateBreak = NA,
        ..rotateLabels = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..lineWidth = NA,
        ..ylabel = NA)
)

areachartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "areachartResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Area Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "mode",
                    "var",
                    "vars",
                    "timeVar",
                    "timeVar1",
                    "group",
                    "colorPalette",
                    "showLine",
                    "isDate",
                    "dateFormat",
                    "dateBreak",
                    "displayFormat",
                    "rotateLabels",
                    "plotWidth",
                    "plotHeight",
                    "dotSize",
                    "lineWidth",
                    "position",
                    "ylabel")))}))

areachartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "areachartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "areachart",
                version = c(1,0,0),
                options = options,
                results = areachartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Area Chart
#'
#' 
#' @param mode .
#' @param data .
#' @param timeVar .
#' @param timeVar1 .
#' @param vars .
#' @param var .
#' @param group .
#' @param showLine .
#' @param position .
#' @param colorPalette .
#' @param isDate .
#' @param dateFormat .
#' @param displayFormat .
#' @param dateBreak .
#' @param rotateLabels .
#' @param plotWidth .
#' @param plotHeight .
#' @param lineWidth .
#' @param ylabel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
areachart <- function(
    mode,
    data,
    timeVar,
    timeVar1,
    vars,
    var,
    group,
    showLine = TRUE,
    position = "stack",
    colorPalette = "jmv",
    isDate = FALSE,
    dateFormat = "auto",
    displayFormat = "%Y-%m-%d",
    dateBreak = "1 month",
    rotateLabels = FALSE,
    plotWidth = 0,
    plotHeight = 0,
    lineWidth = 0.5,
    ylabel) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("areachart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(timeVar)) timeVar <- jmvcore::resolveQuo(jmvcore::enquo(timeVar))
    if ( ! missing(timeVar1)) timeVar1 <- jmvcore::resolveQuo(jmvcore::enquo(timeVar1))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(timeVar), timeVar, NULL),
            `if`( ! missing(timeVar1), timeVar1, NULL),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- areachartOptions$new(
        mode = mode,
        timeVar = timeVar,
        timeVar1 = timeVar1,
        vars = vars,
        var = var,
        group = group,
        showLine = showLine,
        position = position,
        colorPalette = colorPalette,
        isDate = isDate,
        dateFormat = dateFormat,
        displayFormat = displayFormat,
        dateBreak = dateBreak,
        rotateLabels = rotateLabels,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        lineWidth = lineWidth,
        ylabel = ylabel)

    analysis <- areachartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

