
# This file is automatically generated, you probably don't want to edit this

barplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            columns = NULL,
            panel = NULL,
            ignoreNA = TRUE,
            horizontal = FALSE,
            legendAtBottom = FALSE,
            showLabels = TRUE,
            order = "none",
            yaxis1var = "count",
            singleColor = TRUE,
            position = "dodge",
            colorPalette = NULL,
            borderColor = "none",
            textColor = "white",
            accuracy = "0.1",
            plotWidth = 0,
            plotHeight = 0,
            facetBy = "column",
            facetNumber = 1, ...) {

            super$initialize(
                package="vijPlots",
                name="barplot",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..columns <- jmvcore::OptionVariable$new(
                "columns",
                columns,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..panel <- jmvcore::OptionVariable$new(
                "panel",
                panel,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..legendAtBottom <- jmvcore::OptionBool$new(
                "legendAtBottom",
                legendAtBottom,
                default=FALSE)
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..yaxis1var <- jmvcore::OptionList$new(
                "yaxis1var",
                yaxis1var,
                options=list(
                    "count",
                    "percent"),
                default="count")
            private$..singleColor <- jmvcore::OptionBool$new(
                "singleColor",
                singleColor,
                default=TRUE)
            private$..position <- jmvcore::OptionList$new(
                "position",
                position,
                options=list(
                    "dodge",
                    "dodge2",
                    "stack",
                    "fill"),
                default="dodge")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"))
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="none")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "gray"),
                default="white")
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1",
                    "0.01"),
                default="0.1")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionNumber$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)

            self$.addOption(private$..rows)
            self$.addOption(private$..columns)
            self$.addOption(private$..panel)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..legendAtBottom)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..order)
            self$.addOption(private$..yaxis1var)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..position)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
        }),
    active = list(
        rows = function() private$..rows$value,
        columns = function() private$..columns$value,
        panel = function() private$..panel$value,
        ignoreNA = function() private$..ignoreNA$value,
        horizontal = function() private$..horizontal$value,
        legendAtBottom = function() private$..legendAtBottom$value,
        showLabels = function() private$..showLabels$value,
        order = function() private$..order$value,
        yaxis1var = function() private$..yaxis1var$value,
        singleColor = function() private$..singleColor$value,
        position = function() private$..position$value,
        colorPalette = function() private$..colorPalette$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value,
        accuracy = function() private$..accuracy$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value),
    private = list(
        ..rows = NA,
        ..columns = NA,
        ..panel = NA,
        ..ignoreNA = NA,
        ..horizontal = NA,
        ..legendAtBottom = NA,
        ..showLabels = NA,
        ..order = NA,
        ..yaxis1var = NA,
        ..singleColor = NA,
        ..position = NA,
        ..colorPalette = NA,
        ..borderColor = NA,
        ..textColor = NA,
        ..accuracy = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..facetBy = NA,
        ..facetNumber = NA)
)

barplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "rows",
                    "columns",
                    "panel",
                    "ignoreNA",
                    "horizontal",
                    "legendAtBottom",
                    "showLabels",
                    "position",
                    "order",
                    "yaxis1var",
                    "singleColor",
                    "colorPalette",
                    "textColor",
                    "borderColor",
                    "accuracy",
                    "plotWidth",
                    "plotHeight",
                    "facetBy",
                    "facetNumber")))}))

barplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "barplot",
                version = c(1,0,0),
                options = options,
                results = barplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bar Plot
#'
#' 
#' @param data .
#' @param rows .
#' @param columns .
#' @param panel .
#' @param ignoreNA .
#' @param horizontal .
#' @param legendAtBottom .
#' @param showLabels .
#' @param order .
#' @param yaxis1var .
#' @param singleColor .
#' @param position .
#' @param colorPalette .
#' @param borderColor .
#' @param textColor .
#' @param accuracy .
#' @param plotWidth .
#' @param plotHeight .
#' @param facetBy .
#' @param facetNumber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
barplot <- function(
    data,
    rows,
    columns,
    panel,
    ignoreNA = TRUE,
    horizontal = FALSE,
    legendAtBottom = FALSE,
    showLabels = TRUE,
    order = "none",
    yaxis1var = "count",
    singleColor = TRUE,
    position = "dodge",
    colorPalette,
    borderColor = "none",
    textColor = "white",
    accuracy = "0.1",
    plotWidth = 0,
    plotHeight = 0,
    facetBy = "column",
    facetNumber = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("barplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(columns)) columns <- jmvcore::resolveQuo(jmvcore::enquo(columns))
    if ( ! missing(panel)) panel <- jmvcore::resolveQuo(jmvcore::enquo(panel))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(columns), columns, NULL),
            `if`( ! missing(panel), panel, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in columns) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in panel) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barplotOptions$new(
        rows = rows,
        columns = columns,
        panel = panel,
        ignoreNA = ignoreNA,
        horizontal = horizontal,
        legendAtBottom = legendAtBottom,
        showLabels = showLabels,
        order = order,
        yaxis1var = yaxis1var,
        singleColor = singleColor,
        position = position,
        colorPalette = colorPalette,
        borderColor = borderColor,
        textColor = textColor,
        accuracy = accuracy,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        facetBy = facetBy,
        facetNumber = facetNumber)

    analysis <- barplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

