
# This file is automatically generated, you probably don't want to edit this

boxplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            label = NULL,
            showOutliers = TRUE,
            showMean = FALSE,
            staple = FALSE,
            notches = FALSE,
            ignoreNA = TRUE,
            horizontal = FALSE,
            legendAtBottom = FALSE,
            colorPalette = "jmv",
            singleColor = FALSE,
            order = "none",
            plotWidth = 0,
            plotHeight = 0,
            stapleWidth = 0.25,
            notchWidth = 0.5, ...) {

            super$initialize(
                package="vijPlots",
                name="boxplot",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..label <- jmvcore::OptionVariable$new(
                "label",
                label,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..showOutliers <- jmvcore::OptionBool$new(
                "showOutliers",
                showOutliers,
                default=TRUE)
            private$..showMean <- jmvcore::OptionBool$new(
                "showMean",
                showMean,
                default=FALSE)
            private$..staple <- jmvcore::OptionBool$new(
                "staple",
                staple,
                default=FALSE)
            private$..notches <- jmvcore::OptionBool$new(
                "notches",
                notches,
                default=FALSE)
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..legendAtBottom <- jmvcore::OptionBool$new(
                "legendAtBottom",
                legendAtBottom,
                default=FALSE)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"),
                default="jmv")
            private$..singleColor <- jmvcore::OptionBool$new(
                "singleColor",
                singleColor,
                default=FALSE)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..stapleWidth <- jmvcore::OptionNumber$new(
                "stapleWidth",
                stapleWidth,
                min=0,
                max=1,
                default=0.25)
            private$..notchWidth <- jmvcore::OptionNumber$new(
                "notchWidth",
                notchWidth,
                min=0,
                max=1,
                default=0.5)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..label)
            self$.addOption(private$..showOutliers)
            self$.addOption(private$..showMean)
            self$.addOption(private$..staple)
            self$.addOption(private$..notches)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..legendAtBottom)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..order)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..stapleWidth)
            self$.addOption(private$..notchWidth)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        label = function() private$..label$value,
        showOutliers = function() private$..showOutliers$value,
        showMean = function() private$..showMean$value,
        staple = function() private$..staple$value,
        notches = function() private$..notches$value,
        ignoreNA = function() private$..ignoreNA$value,
        horizontal = function() private$..horizontal$value,
        legendAtBottom = function() private$..legendAtBottom$value,
        colorPalette = function() private$..colorPalette$value,
        singleColor = function() private$..singleColor$value,
        order = function() private$..order$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        stapleWidth = function() private$..stapleWidth$value,
        notchWidth = function() private$..notchWidth$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..label = NA,
        ..showOutliers = NA,
        ..showMean = NA,
        ..staple = NA,
        ..notches = NA,
        ..ignoreNA = NA,
        ..horizontal = NA,
        ..legendAtBottom = NA,
        ..colorPalette = NA,
        ..singleColor = NA,
        ..order = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..stapleWidth = NA,
        ..notchWidth = NA)
)

boxplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Box Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "group",
                    "label",
                    "showOutliers",
                    "showMean",
                    "staple",
                    "notches",
                    "horizontal",
                    "legendAtBottom",
                    "ignoreNA",
                    "stapleWidth",
                    "notchWidth",
                    "colorPalette",
                    "singleColor",
                    "order",
                    "plotHeight",
                    "plotWidth")))}))

boxplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "boxplot",
                version = c(1,0,0),
                options = options,
                results = boxplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Box Plot
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param label .
#' @param showOutliers .
#' @param showMean .
#' @param staple .
#' @param notches .
#' @param ignoreNA .
#' @param horizontal .
#' @param legendAtBottom .
#' @param colorPalette .
#' @param singleColor .
#' @param order .
#' @param plotWidth .
#' @param plotHeight .
#' @param stapleWidth .
#' @param notchWidth .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
boxplot <- function(
    data,
    vars,
    group,
    label,
    showOutliers = TRUE,
    showMean = FALSE,
    staple = FALSE,
    notches = FALSE,
    ignoreNA = TRUE,
    horizontal = FALSE,
    legendAtBottom = FALSE,
    colorPalette = "jmv",
    singleColor = FALSE,
    order = "none",
    plotWidth = 0,
    plotHeight = 0,
    stapleWidth = 0.25,
    notchWidth = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("boxplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(label)) label <- jmvcore::resolveQuo(jmvcore::enquo(label))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(label), label, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- boxplotOptions$new(
        vars = vars,
        group = group,
        label = label,
        showOutliers = showOutliers,
        showMean = showMean,
        staple = staple,
        notches = notches,
        ignoreNA = ignoreNA,
        horizontal = horizontal,
        legendAtBottom = legendAtBottom,
        colorPalette = colorPalette,
        singleColor = singleColor,
        order = order,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        stapleWidth = stapleWidth,
        notchWidth = notchWidth)

    analysis <- boxplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

