
# This file is automatically generated, you probably don't want to edit this

correspOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            showContingency = FALSE,
            showProfiles = FALSE,
            showInertia = TRUE,
            showSummaries = FALSE,
            showRowPlot = FALSE,
            showColPlot = FALSE,
            showBiPlot = TRUE,
            supplementaryRows = NULL,
            supplementaryCols = NULL,
            dimNum = 2,
            xaxis = 1,
            yaxis = 2,
            normalization = "principal",
            plotWidth = 600,
            plotHeight = 450,
            fixedRatio = TRUE,
            rowColor = "blue",
            colColor = "red",
            supColor = "darkgray", ...) {

            super$initialize(
                package="vijPlots",
                name="corresp",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..showContingency <- jmvcore::OptionBool$new(
                "showContingency",
                showContingency,
                default=FALSE)
            private$..showProfiles <- jmvcore::OptionBool$new(
                "showProfiles",
                showProfiles,
                default=FALSE)
            private$..showInertia <- jmvcore::OptionBool$new(
                "showInertia",
                showInertia,
                default=TRUE)
            private$..showSummaries <- jmvcore::OptionBool$new(
                "showSummaries",
                showSummaries,
                default=FALSE)
            private$..showRowPlot <- jmvcore::OptionBool$new(
                "showRowPlot",
                showRowPlot,
                default=FALSE)
            private$..showColPlot <- jmvcore::OptionBool$new(
                "showColPlot",
                showColPlot,
                default=FALSE)
            private$..showBiPlot <- jmvcore::OptionBool$new(
                "showBiPlot",
                showBiPlot,
                default=TRUE)
            private$..supplementaryRows <- jmvcore::OptionString$new(
                "supplementaryRows",
                supplementaryRows)
            private$..supplementaryCols <- jmvcore::OptionString$new(
                "supplementaryCols",
                supplementaryCols)
            private$..dimNum <- jmvcore::OptionNumber$new(
                "dimNum",
                dimNum,
                min=2,
                max=10,
                default=2)
            private$..xaxis <- jmvcore::OptionNumber$new(
                "xaxis",
                xaxis,
                min=1,
                max=10,
                default=1)
            private$..yaxis <- jmvcore::OptionNumber$new(
                "yaxis",
                yaxis,
                min=1,
                max=10,
                default=2)
            private$..normalization <- jmvcore::OptionList$new(
                "normalization",
                normalization,
                options=list(
                    "principal",
                    "symbiplot",
                    "rowprincipal",
                    "colprincipal",
                    "standard"),
                default="principal")
            private$..plotWidth <- jmvcore::OptionInteger$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=600)
            private$..plotHeight <- jmvcore::OptionInteger$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1000,
                default=450)
            private$..fixedRatio <- jmvcore::OptionBool$new(
                "fixedRatio",
                fixedRatio,
                default=TRUE)
            private$..rowColor <- jmvcore::OptionList$new(
                "rowColor",
                rowColor,
                options=list(
                    "blue",
                    "red",
                    "forestgreen",
                    "purple",
                    "hotpink",
                    "darkorange1"),
                default="blue")
            private$..colColor <- jmvcore::OptionList$new(
                "colColor",
                colColor,
                options=list(
                    "blue",
                    "red",
                    "forestgreen",
                    "purple",
                    "hotpink",
                    "darkorange1"),
                default="red")
            private$..supColor <- jmvcore::OptionList$new(
                "supColor",
                supColor,
                options=list(
                    "darkgray",
                    "black",
                    "yellow2",
                    "white"),
                default="darkgray")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..showContingency)
            self$.addOption(private$..showProfiles)
            self$.addOption(private$..showInertia)
            self$.addOption(private$..showSummaries)
            self$.addOption(private$..showRowPlot)
            self$.addOption(private$..showColPlot)
            self$.addOption(private$..showBiPlot)
            self$.addOption(private$..supplementaryRows)
            self$.addOption(private$..supplementaryCols)
            self$.addOption(private$..dimNum)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..normalization)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..fixedRatio)
            self$.addOption(private$..rowColor)
            self$.addOption(private$..colColor)
            self$.addOption(private$..supColor)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        showContingency = function() private$..showContingency$value,
        showProfiles = function() private$..showProfiles$value,
        showInertia = function() private$..showInertia$value,
        showSummaries = function() private$..showSummaries$value,
        showRowPlot = function() private$..showRowPlot$value,
        showColPlot = function() private$..showColPlot$value,
        showBiPlot = function() private$..showBiPlot$value,
        supplementaryRows = function() private$..supplementaryRows$value,
        supplementaryCols = function() private$..supplementaryCols$value,
        dimNum = function() private$..dimNum$value,
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        normalization = function() private$..normalization$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        fixedRatio = function() private$..fixedRatio$value,
        rowColor = function() private$..rowColor$value,
        colColor = function() private$..colColor$value,
        supColor = function() private$..supColor$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..showContingency = NA,
        ..showProfiles = NA,
        ..showInertia = NA,
        ..showSummaries = NA,
        ..showRowPlot = NA,
        ..showColPlot = NA,
        ..showBiPlot = NA,
        ..supplementaryRows = NA,
        ..supplementaryCols = NA,
        ..dimNum = NA,
        ..xaxis = NA,
        ..yaxis = NA,
        ..normalization = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..fixedRatio = NA,
        ..rowColor = NA,
        ..colColor = NA,
        ..supColor = NA)
)

correspResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspResults",
    inherit = jmvcore::Group,
    active = list(
        helpMessage = function() private$.items[["helpMessage"]],
        contingency = function() private$.items[["contingency"]],
        rowProfiles = function() private$.items[["rowProfiles"]],
        colProfiles = function() private$.items[["colProfiles"]],
        eigenvalues = function() private$.items[["eigenvalues"]],
        rowSummary = function() private$.items[["rowSummary"]],
        colSummary = function() private$.items[["colSummary"]],
        rowplot = function() private$.items[["rowplot"]],
        colplot = function() private$.items[["colplot"]],
        biplot = function() private$.items[["biplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correspondence Plot",
                refs=list(
                    "ca"))
            self$add(jmvcore::Html$new(
                options=options,
                name="helpMessage",
                title="",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="contingency",
                title="Contingency Table",
                visible="(showContingency)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowProfiles",
                title="Row Profiles",
                visible="(showProfiles)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="colProfiles",
                title="Column Profiles",
                visible="(showProfiles)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigenvalues",
                title="Summary",
                visible="(showInertia)",
                rows=0,
                columns=list(
                    list(
                        `name`="dim", 
                        `title`="Dimension", 
                        `type`="number"),
                    list(
                        `name`="singular", 
                        `title`="Singular Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="inertia", 
                        `title`="Inertia", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="proportion", 
                        `title`="% of Inertia", 
                        `type`="integer", 
                        `format`="pc"),
                    list(
                        `name`="cumulative", 
                        `title`="Cumulative %", 
                        `type`="number", 
                        `format`="pc")),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowSummary",
                title="Row Summary",
                rows=0,
                visible="(showSummaries)",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "dimNum",
                    "normalization")))
            self$add(jmvcore::Table$new(
                options=options,
                name="colSummary",
                title="Column Summary",
                rows=0,
                visible="(showSummaries)",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "dimNum",
                    "normalization")))
            self$add(jmvcore::Image$new(
                options=options,
                name="rowplot",
                title="Row Plot",
                visible="(showRowPlot)",
                width=600,
                height=450,
                renderFun=".rowplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "xaxis",
                    "yaxis",
                    "rowColor",
                    "supColor",
                    "plotWidth",
                    "plotHeight",
                    "fixedRatio",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization")))
            self$add(jmvcore::Image$new(
                options=options,
                name="colplot",
                title="Column Plot",
                visible="(showColPlot)",
                width=600,
                height=450,
                renderFun=".colplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "xaxis",
                    "yaxis",
                    "colColor",
                    "supColor",
                    "plotWidth",
                    "plotHeight",
                    "fixedRatio",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biplot",
                title="Biplot",
                visible="(showBiPlot)",
                width=600,
                height=450,
                renderFun=".biplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "xaxis",
                    "yaxis",
                    "rowColor",
                    "colColor",
                    "supColor",
                    "plotWidth",
                    "plotHeight",
                    "fixedRatio",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization")))}))

correspBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "corresp",
                version = c(1,0,0),
                options = options,
                results = correspResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Correspondence Plot
#'
#' 
#' @param data .
#' @param rows .
#' @param cols .
#' @param counts .
#' @param showContingency .
#' @param showProfiles .
#' @param showInertia .
#' @param showSummaries .
#' @param showRowPlot .
#' @param showColPlot .
#' @param showBiPlot .
#' @param supplementaryRows .
#' @param supplementaryCols .
#' @param dimNum .
#' @param xaxis .
#' @param yaxis .
#' @param normalization .
#' @param plotWidth .
#' @param plotHeight .
#' @param fixedRatio .
#' @param rowColor .
#' @param colColor .
#' @param supColor .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$helpMessage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$contingency} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowProfiles} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colProfiles} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eigenvalues} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$colplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$contingency$asDF}
#'
#' \code{as.data.frame(results$contingency)}
#'
#' @export
corresp <- function(
    data,
    rows,
    cols,
    counts,
    showContingency = FALSE,
    showProfiles = FALSE,
    showInertia = TRUE,
    showSummaries = FALSE,
    showRowPlot = FALSE,
    showColPlot = FALSE,
    showBiPlot = TRUE,
    supplementaryRows,
    supplementaryCols,
    dimNum = 2,
    xaxis = 1,
    yaxis = 2,
    normalization = "principal",
    plotWidth = 600,
    plotHeight = 450,
    fixedRatio = TRUE,
    rowColor = "blue",
    colColor = "red",
    supColor = "darkgray") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("corresp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- correspOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        showContingency = showContingency,
        showProfiles = showProfiles,
        showInertia = showInertia,
        showSummaries = showSummaries,
        showRowPlot = showRowPlot,
        showColPlot = showColPlot,
        showBiPlot = showBiPlot,
        supplementaryRows = supplementaryRows,
        supplementaryCols = supplementaryCols,
        dimNum = dimNum,
        xaxis = xaxis,
        yaxis = yaxis,
        normalization = normalization,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        fixedRatio = fixedRatio,
        rowColor = rowColor,
        colColor = colColor,
        supColor = supColor)

    analysis <- correspClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

