
# This file is automatically generated, you probably don't want to edit this

linechartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linechartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            timeVar = NULL,
            vars = NULL,
            group = NULL,
            showPoint = TRUE,
            colorPalette = "jmv",
            isDate = FALSE,
            dateFormat = "auto",
            displayFormat = "%Y-%m-%d",
            dateBreak = "1 month",
            rotateLabels = FALSE,
            plotWidth = 0,
            plotHeight = 0,
            dotSize = 2,
            lineWidth = 1, ...) {

            super$initialize(
                package="vijPlots",
                name="linechart",
                requiresData=TRUE,
                ...)

            private$..timeVar <- jmvcore::OptionVariable$new(
                "timeVar",
                timeVar,
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..showPoint <- jmvcore::OptionBool$new(
                "showPoint",
                showPoint,
                default=TRUE)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"),
                default="jmv")
            private$..isDate <- jmvcore::OptionBool$new(
                "isDate",
                isDate,
                default=FALSE)
            private$..dateFormat <- jmvcore::OptionList$new(
                "dateFormat",
                dateFormat,
                options=list(
                    "auto",
                    "iso",
                    "us",
                    "eu"),
                default="auto")
            private$..displayFormat <- jmvcore::OptionList$new(
                "displayFormat",
                displayFormat,
                options=list(
                    "%Y-%m-%d",
                    "%m/%d/%y",
                    "%d/%m/%y",
                    "%Y %B %e ",
                    "%e %B %Y",
                    "%B %Y",
                    "%Y %B",
                    "%b",
                    "%B",
                    "%Y"),
                default="%Y-%m-%d")
            private$..dateBreak <- jmvcore::OptionList$new(
                "dateBreak",
                dateBreak,
                options=list(
                    "1 day",
                    "1 week",
                    "2 week",
                    "1 month",
                    "3 month",
                    "6 month",
                    "1 year",
                    "10 year"),
                default="1 month")
            private$..rotateLabels <- jmvcore::OptionBool$new(
                "rotateLabels",
                rotateLabels,
                default=FALSE)
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1000,
                default=0)
            private$..dotSize <- jmvcore::OptionNumber$new(
                "dotSize",
                dotSize,
                min=1,
                max=20,
                default=2)
            private$..lineWidth <- jmvcore::OptionNumber$new(
                "lineWidth",
                lineWidth,
                min=0,
                max=10,
                default=1)

            self$.addOption(private$..timeVar)
            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..showPoint)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..isDate)
            self$.addOption(private$..dateFormat)
            self$.addOption(private$..displayFormat)
            self$.addOption(private$..dateBreak)
            self$.addOption(private$..rotateLabels)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..dotSize)
            self$.addOption(private$..lineWidth)
        }),
    active = list(
        timeVar = function() private$..timeVar$value,
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        showPoint = function() private$..showPoint$value,
        colorPalette = function() private$..colorPalette$value,
        isDate = function() private$..isDate$value,
        dateFormat = function() private$..dateFormat$value,
        displayFormat = function() private$..displayFormat$value,
        dateBreak = function() private$..dateBreak$value,
        rotateLabels = function() private$..rotateLabels$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        dotSize = function() private$..dotSize$value,
        lineWidth = function() private$..lineWidth$value),
    private = list(
        ..timeVar = NA,
        ..vars = NA,
        ..group = NA,
        ..showPoint = NA,
        ..colorPalette = NA,
        ..isDate = NA,
        ..dateFormat = NA,
        ..displayFormat = NA,
        ..dateBreak = NA,
        ..rotateLabels = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..dotSize = NA,
        ..lineWidth = NA)
)

linechartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linechartResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Line Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "timeVar",
                    "group",
                    "colorPalette",
                    "lineType",
                    "showPoint",
                    "isDate",
                    "dateFormat",
                    "dateBreak",
                    "displayFormat",
                    "rotateLabels",
                    "plotWidth",
                    "plotHeight",
                    "dotSize",
                    "lineWidth")))}))

linechartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linechartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "linechart",
                version = c(1,0,0),
                options = options,
                results = linechartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Line Chart
#'
#' 
#' @param data .
#' @param timeVar .
#' @param vars .
#' @param group .
#' @param showPoint .
#' @param colorPalette .
#' @param isDate .
#' @param dateFormat .
#' @param displayFormat .
#' @param dateBreak .
#' @param rotateLabels .
#' @param plotWidth .
#' @param plotHeight .
#' @param dotSize .
#' @param lineWidth .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
linechart <- function(
    data,
    timeVar,
    vars,
    group,
    showPoint = TRUE,
    colorPalette = "jmv",
    isDate = FALSE,
    dateFormat = "auto",
    displayFormat = "%Y-%m-%d",
    dateBreak = "1 month",
    rotateLabels = FALSE,
    plotWidth = 0,
    plotHeight = 0,
    dotSize = 2,
    lineWidth = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("linechart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(timeVar)) timeVar <- jmvcore::resolveQuo(jmvcore::enquo(timeVar))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(timeVar), timeVar, NULL),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- linechartOptions$new(
        timeVar = timeVar,
        vars = vars,
        group = group,
        showPoint = showPoint,
        colorPalette = colorPalette,
        isDate = isDate,
        dateFormat = dateFormat,
        displayFormat = displayFormat,
        dateBreak = dateBreak,
        rotateLabels = rotateLabels,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        dotSize = dotSize,
        lineWidth = lineWidth)

    analysis <- linechartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

