
# This file is automatically generated, you probably don't want to edit this

lollipopOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lollipopOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aVar = NULL,
            group = NULL,
            facet = NULL,
            yaxis = "mean",
            order = "none",
            horizontal = FALSE,
            dotColor = "#E41A1C",
            lineColor = "black",
            dotSize = 4,
            lineWidth = 0.5,
            plotWidth = 0,
            plotHeight = 0,
            facetBy = "column",
            facetNumber = 1, ...) {

            super$initialize(
                package="vijPlots",
                name="lollipop",
                requiresData=TRUE,
                ...)

            private$..aVar <- jmvcore::OptionVariable$new(
                "aVar",
                aVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "mean",
                    "median",
                    "max",
                    "min",
                    "minmax",
                    "identity"),
                default="mean")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..dotColor <- jmvcore::OptionList$new(
                "dotColor",
                dotColor,
                options=list(
                    "white",
                    "black",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#FBB4AE",
                    "#B3CDE3",
                    "#CCEBC5",
                    "#DECBE4",
                    "#FED9A6",
                    "#FFFFCC",
                    "#E5D8BD",
                    "#FDDAEC",
                    "#F2F2F2"),
                default="#E41A1C")
            private$..lineColor <- jmvcore::OptionList$new(
                "lineColor",
                lineColor,
                options=list(
                    "white",
                    "black",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#FBB4AE",
                    "#B3CDE3",
                    "#CCEBC5",
                    "#DECBE4",
                    "#FED9A6",
                    "#FFFFCC",
                    "#E5D8BD",
                    "#FDDAEC",
                    "#F2F2F2"),
                default="black")
            private$..dotSize <- jmvcore::OptionNumber$new(
                "dotSize",
                dotSize,
                min=1,
                max=20,
                default=4)
            private$..lineWidth <- jmvcore::OptionNumber$new(
                "lineWidth",
                lineWidth,
                min=0.1,
                max=10,
                default=0.5)
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionNumber$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)

            self$.addOption(private$..aVar)
            self$.addOption(private$..group)
            self$.addOption(private$..facet)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..order)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..dotColor)
            self$.addOption(private$..lineColor)
            self$.addOption(private$..dotSize)
            self$.addOption(private$..lineWidth)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
        }),
    active = list(
        aVar = function() private$..aVar$value,
        group = function() private$..group$value,
        facet = function() private$..facet$value,
        yaxis = function() private$..yaxis$value,
        order = function() private$..order$value,
        horizontal = function() private$..horizontal$value,
        dotColor = function() private$..dotColor$value,
        lineColor = function() private$..lineColor$value,
        dotSize = function() private$..dotSize$value,
        lineWidth = function() private$..lineWidth$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value),
    private = list(
        ..aVar = NA,
        ..group = NA,
        ..facet = NA,
        ..yaxis = NA,
        ..order = NA,
        ..horizontal = NA,
        ..dotColor = NA,
        ..lineColor = NA,
        ..dotSize = NA,
        ..lineWidth = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..facetBy = NA,
        ..facetNumber = NA)
)

lollipopResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lollipopResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Lollipop Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "aVar",
                    "group",
                    "facet",
                    "yaxis",
                    "order",
                    "horizontal",
                    "dotColor",
                    "lineColor",
                    "dotSize",
                    "lineWidth",
                    "facetBy",
                    "facetNumber",
                    "plotWidth",
                    "plotHeight")))}))

lollipopBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lollipopBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "lollipop",
                version = c(1,0,0),
                options = options,
                results = lollipopResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Lollipop Plot
#'
#' 
#' @param data .
#' @param aVar .
#' @param group .
#' @param facet .
#' @param yaxis .
#' @param order .
#' @param horizontal .
#' @param dotColor .
#' @param lineColor .
#' @param dotSize .
#' @param lineWidth .
#' @param plotWidth .
#' @param plotHeight .
#' @param facetBy .
#' @param facetNumber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
lollipop <- function(
    data,
    aVar,
    group,
    facet,
    yaxis = "mean",
    order = "none",
    horizontal = FALSE,
    dotColor = "#E41A1C",
    lineColor = "black",
    dotSize = 4,
    lineWidth = 0.5,
    plotWidth = 0,
    plotHeight = 0,
    facetBy = "column",
    facetNumber = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lollipop requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aVar)) aVar <- jmvcore::resolveQuo(jmvcore::enquo(aVar))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aVar), aVar, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lollipopOptions$new(
        aVar = aVar,
        group = group,
        facet = facet,
        yaxis = yaxis,
        order = order,
        horizontal = horizontal,
        dotColor = dotColor,
        lineColor = lineColor,
        dotSize = dotSize,
        lineWidth = lineWidth,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        facetBy = facetBy,
        facetNumber = facetNumber)

    analysis <- lollipopClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

