
# This file is automatically generated, you probably don't want to edit this

piechartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aVar = NULL,
            panel = NULL,
            donut = FALSE,
            legendBottom = FALSE,
            showLabels = FALSE,
            labels = "count",
            colorPalette = NULL,
            borderColor = "black",
            textColor = "black", ...) {

            super$initialize(
                package="vijPlots",
                name="piechart",
                requiresData=TRUE,
                ...)

            private$..aVar <- jmvcore::OptionVariable$new(
                "aVar",
                aVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..panel <- jmvcore::OptionVariable$new(
                "panel",
                panel,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..donut <- jmvcore::OptionBool$new(
                "donut",
                donut,
                default=FALSE)
            private$..legendBottom <- jmvcore::OptionBool$new(
                "legendBottom",
                legendBottom,
                default=FALSE)
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=FALSE)
            private$..labels <- jmvcore::OptionList$new(
                "labels",
                labels,
                options=list(
                    "count",
                    "percent"),
                default="count")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"))
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="black")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "gray"),
                default="black")

            self$.addOption(private$..aVar)
            self$.addOption(private$..panel)
            self$.addOption(private$..donut)
            self$.addOption(private$..legendBottom)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..labels)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
        }),
    active = list(
        aVar = function() private$..aVar$value,
        panel = function() private$..panel$value,
        donut = function() private$..donut$value,
        legendBottom = function() private$..legendBottom$value,
        showLabels = function() private$..showLabels$value,
        labels = function() private$..labels$value,
        colorPalette = function() private$..colorPalette$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value),
    private = list(
        ..aVar = NA,
        ..panel = NA,
        ..donut = NA,
        ..legendBottom = NA,
        ..showLabels = NA,
        ..labels = NA,
        ..colorPalette = NA,
        ..borderColor = NA,
        ..textColor = NA)
)

piechartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pie Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "aVar",
                    "panel",
                    "donut",
                    "legendBottom",
                    "showLabels",
                    "labels",
                    "colorPalette",
                    "borderColor",
                    "textColor")))}))

piechartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "piechart",
                version = c(1,0,0),
                options = options,
                results = piechartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Pie Chart
#'
#' 
#' @param data .
#' @param aVar .
#' @param panel .
#' @param donut .
#' @param legendBottom .
#' @param showLabels .
#' @param labels .
#' @param colorPalette .
#' @param borderColor .
#' @param textColor .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
piechart <- function(
    data,
    aVar,
    panel,
    donut = FALSE,
    legendBottom = FALSE,
    showLabels = FALSE,
    labels = "count",
    colorPalette,
    borderColor = "black",
    textColor = "black") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("piechart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aVar)) aVar <- jmvcore::resolveQuo(jmvcore::enquo(aVar))
    if ( ! missing(panel)) panel <- jmvcore::resolveQuo(jmvcore::enquo(panel))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aVar), aVar, NULL),
            `if`( ! missing(panel), panel, NULL))

    for (v in aVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in panel) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- piechartOptions$new(
        aVar = aVar,
        panel = panel,
        donut = donut,
        legendBottom = legendBottom,
        showLabels = showLabels,
        labels = labels,
        colorPalette = colorPalette,
        borderColor = borderColor,
        textColor = textColor)

    analysis <- piechartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

