
# This file is automatically generated, you probably don't want to edit this

piechartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aVar = NULL,
            facet = NULL,
            donut = FALSE,
            legendBottom = FALSE,
            labels = "none",
            colorPalette = NULL,
            borderColor = "black",
            textColor = "black",
            accuracy = "0.1",
            plotWidth = 0,
            plotHeight = 0,
            facetBy = "column",
            facetNumber = 1, ...) {

            super$initialize(
                package="vijPlots",
                name="piechart",
                requiresData=TRUE,
                ...)

            private$..aVar <- jmvcore::OptionVariable$new(
                "aVar",
                aVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..donut <- jmvcore::OptionBool$new(
                "donut",
                donut,
                default=FALSE)
            private$..legendBottom <- jmvcore::OptionBool$new(
                "legendBottom",
                legendBottom,
                default=FALSE)
            private$..labels <- jmvcore::OptionList$new(
                "labels",
                labels,
                options=list(
                    "none",
                    "count",
                    "percent"),
                default="none")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"))
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="black")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "gray"),
                default="black")
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1",
                    "0.01"),
                default="0.1")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionNumber$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)

            self$.addOption(private$..aVar)
            self$.addOption(private$..facet)
            self$.addOption(private$..donut)
            self$.addOption(private$..legendBottom)
            self$.addOption(private$..labels)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
        }),
    active = list(
        aVar = function() private$..aVar$value,
        facet = function() private$..facet$value,
        donut = function() private$..donut$value,
        legendBottom = function() private$..legendBottom$value,
        labels = function() private$..labels$value,
        colorPalette = function() private$..colorPalette$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value,
        accuracy = function() private$..accuracy$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value),
    private = list(
        ..aVar = NA,
        ..facet = NA,
        ..donut = NA,
        ..legendBottom = NA,
        ..labels = NA,
        ..colorPalette = NA,
        ..borderColor = NA,
        ..textColor = NA,
        ..accuracy = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..facetBy = NA,
        ..facetNumber = NA)
)

piechartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pie Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "aVar",
                    "facet",
                    "donut",
                    "legendBottom",
                    "labels",
                    "colorPalette",
                    "borderColor",
                    "textColor",
                    "accuracy",
                    "plotWidth",
                    "plotHeight",
                    "facetBy",
                    "facetNumber")))}))

piechartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "piechartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "piechart",
                version = c(1,0,0),
                options = options,
                results = piechartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Pie Chart
#'
#' 
#' @param data .
#' @param aVar .
#' @param facet .
#' @param donut .
#' @param legendBottom .
#' @param labels .
#' @param colorPalette .
#' @param borderColor .
#' @param textColor .
#' @param accuracy .
#' @param plotWidth .
#' @param plotHeight .
#' @param facetBy .
#' @param facetNumber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
piechart <- function(
    data,
    aVar,
    facet,
    donut = FALSE,
    legendBottom = FALSE,
    labels = "none",
    colorPalette,
    borderColor = "black",
    textColor = "black",
    accuracy = "0.1",
    plotWidth = 0,
    plotHeight = 0,
    facetBy = "column",
    facetNumber = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("piechart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aVar)) aVar <- jmvcore::resolveQuo(jmvcore::enquo(aVar))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aVar), aVar, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in aVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- piechartOptions$new(
        aVar = aVar,
        facet = facet,
        donut = donut,
        legendBottom = legendBottom,
        labels = labels,
        colorPalette = colorPalette,
        borderColor = borderColor,
        textColor = textColor,
        accuracy = accuracy,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        facetBy = facetBy,
        facetNumber = facetNumber)

    analysis <- piechartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

