
# This file is automatically generated, you probably don't want to edit this

principalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labelVar = NULL,
            groupVar = NULL,
            rotation = "none",
            dimNum = 2,
            xaxis = 1,
            yaxis = 2,
            showSummary = TRUE,
            showKMO = FALSE,
            showLoadings = FALSE,
            showObservations = FALSE,
            showScreePlot = TRUE,
            showVarPlot = TRUE,
            showObsPlot = TRUE,
            showBiplot = FALSE,
            missingValues = "listwise",
            stdScores = TRUE, ...) {

            super$initialize(
                package="vijPlots",
                name="principal",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rotation <- jmvcore::OptionList$new(
                "rotation",
                rotation,
                options=list(
                    "none",
                    "varimax",
                    "quartimax",
                    "promax",
                    "oblimin",
                    "simplimax"),
                default="none")
            private$..dimNum <- jmvcore::OptionNumber$new(
                "dimNum",
                dimNum,
                min=2,
                max=99,
                default=2)
            private$..xaxis <- jmvcore::OptionNumber$new(
                "xaxis",
                xaxis,
                min=1,
                max=99,
                default=1)
            private$..yaxis <- jmvcore::OptionNumber$new(
                "yaxis",
                yaxis,
                min=1,
                max=99,
                default=2)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..showKMO <- jmvcore::OptionBool$new(
                "showKMO",
                showKMO,
                default=FALSE)
            private$..showLoadings <- jmvcore::OptionBool$new(
                "showLoadings",
                showLoadings,
                default=FALSE)
            private$..showObservations <- jmvcore::OptionBool$new(
                "showObservations",
                showObservations,
                default=FALSE)
            private$..showScreePlot <- jmvcore::OptionBool$new(
                "showScreePlot",
                showScreePlot,
                default=TRUE)
            private$..showVarPlot <- jmvcore::OptionBool$new(
                "showVarPlot",
                showVarPlot,
                default=TRUE)
            private$..showObsPlot <- jmvcore::OptionBool$new(
                "showObsPlot",
                showObsPlot,
                default=TRUE)
            private$..showBiplot <- jmvcore::OptionBool$new(
                "showBiplot",
                showBiplot,
                default=FALSE)
            private$..missingValues <- jmvcore::OptionList$new(
                "missingValues",
                missingValues,
                options=list(
                    "listwise",
                    "pairwise",
                    "mean"),
                default="listwise")
            private$..stdScores <- jmvcore::OptionBool$new(
                "stdScores",
                stdScores,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..rotation)
            self$.addOption(private$..dimNum)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showKMO)
            self$.addOption(private$..showLoadings)
            self$.addOption(private$..showObservations)
            self$.addOption(private$..showScreePlot)
            self$.addOption(private$..showVarPlot)
            self$.addOption(private$..showObsPlot)
            self$.addOption(private$..showBiplot)
            self$.addOption(private$..missingValues)
            self$.addOption(private$..stdScores)
        }),
    active = list(
        vars = function() private$..vars$value,
        labelVar = function() private$..labelVar$value,
        groupVar = function() private$..groupVar$value,
        rotation = function() private$..rotation$value,
        dimNum = function() private$..dimNum$value,
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        showSummary = function() private$..showSummary$value,
        showKMO = function() private$..showKMO$value,
        showLoadings = function() private$..showLoadings$value,
        showObservations = function() private$..showObservations$value,
        showScreePlot = function() private$..showScreePlot$value,
        showVarPlot = function() private$..showVarPlot$value,
        showObsPlot = function() private$..showObsPlot$value,
        showBiplot = function() private$..showBiplot$value,
        missingValues = function() private$..missingValues$value,
        stdScores = function() private$..stdScores$value),
    private = list(
        ..vars = NA,
        ..labelVar = NA,
        ..groupVar = NA,
        ..rotation = NA,
        ..dimNum = NA,
        ..xaxis = NA,
        ..yaxis = NA,
        ..showSummary = NA,
        ..showKMO = NA,
        ..showLoadings = NA,
        ..showObservations = NA,
        ..showScreePlot = NA,
        ..showVarPlot = NA,
        ..showObsPlot = NA,
        ..showBiplot = NA,
        ..missingValues = NA,
        ..stdScores = NA)
)

principalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        summaryTable = function() private$.items[["summaryTable"]],
        kmoTable = function() private$.items[["kmoTable"]],
        loadingTable = function() private$.items[["loadingTable"]],
        obsTable = function() private$.items[["obsTable"]],
        screePlot = function() private$.items[["screePlot"]],
        varPlot = function() private$.items[["varPlot"]],
        obsPlot = function() private$.items[["obsPlot"]],
        biPlot = function() private$.items[["biPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Principal Component Plot",
                refs=list(
                    "psych"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Principal Component Plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Summary",
                visible="(showSummary)",
                clearWith=list(
                    "vars",
                    "dimNum",
                    "rotation",
                    "missingValues"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="initVarProp", 
                        `title`="% of Variance", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="initVarCum", 
                        `title`="Cumulative %", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="loadings", 
                        `title`="SS Loadings", 
                        `superTitle`="Extration Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `superTitle`="Extration Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `superTitle`="Extration Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="kmoTable",
                title="KMO & Bartlett's Test",
                visible="(showKMO)",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto")),
                rows=2,
                clearWith=list(
                    "vars",
                    "missingValues")))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingTable",
                title="Loadings",
                visible="(showLoadings)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "missingValues"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="obsTable",
                title="Observations",
                visible="(showObservations)",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "missingValues",
                    "stdScores"),
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="screePlot",
                title="Scree Plot",
                width=500,
                height=300,
                visible="(showScreePlot)",
                renderFun=".screeplot",
                clearWith=list(
                    "vars",
                    "missingValues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="varPlot",
                title="Loading Plot",
                width=600,
                height=600,
                visible="(showVarPlot)",
                renderFun=".varplot",
                clearWith=list(
                    "vars",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "missingValues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="obsPlot",
                title="Observation Plot",
                width=600,
                height=600,
                visible="(showObsPlot)",
                renderFun=".obsplot",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "missingValues",
                    "groupVar",
                    "stdScores")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biPlot",
                title="Biplot",
                width=600,
                height=600,
                visible="(showBiplot)",
                renderFun=".biplot",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "missingValues",
                    "groupVar",
                    "stdScores")))}))

principalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "principal",
                version = c(1,0,0),
                options = options,
                results = principalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Principal Component Plot
#'
#' 
#' @param data .
#' @param vars .
#' @param labelVar .
#' @param groupVar .
#' @param rotation .
#' @param dimNum .
#' @param xaxis .
#' @param yaxis .
#' @param showSummary .
#' @param showKMO .
#' @param showLoadings .
#' @param showObservations .
#' @param showScreePlot .
#' @param showVarPlot .
#' @param showObsPlot .
#' @param showBiplot .
#' @param missingValues .
#' @param stdScores .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$kmoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$obsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$screePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$varPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$obsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
principal <- function(
    data,
    vars,
    labelVar,
    groupVar,
    rotation = "none",
    dimNum = 2,
    xaxis = 1,
    yaxis = 2,
    showSummary = TRUE,
    showKMO = FALSE,
    showLoadings = FALSE,
    showObservations = FALSE,
    showScreePlot = TRUE,
    showVarPlot = TRUE,
    showObsPlot = TRUE,
    showBiplot = FALSE,
    missingValues = "listwise",
    stdScores = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("principal requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))

    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- principalOptions$new(
        vars = vars,
        labelVar = labelVar,
        groupVar = groupVar,
        rotation = rotation,
        dimNum = dimNum,
        xaxis = xaxis,
        yaxis = yaxis,
        showSummary = showSummary,
        showKMO = showKMO,
        showLoadings = showLoadings,
        showObservations = showObservations,
        showScreePlot = showScreePlot,
        showVarPlot = showVarPlot,
        showObsPlot = showObsPlot,
        showBiplot = showBiplot,
        missingValues = missingValues,
        stdScores = stdScores)

    analysis <- principalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

