
# This file is automatically generated, you probably don't want to edit this

qqplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            distrib = "norm",
            transLog = FALSE,
            standardize = FALSE,
            refLine = TRUE,
            band = FALSE,
            methodQQ = "ell",
            methodPP = "ell",
            detrend = FALSE,
            type = "QQ",
            refType = "identity",
            plotWidth = 0,
            plotHeight = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="qqplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..distrib <- jmvcore::OptionList$new(
                "distrib",
                distrib,
                options=list(
                    "norm",
                    "lnorm",
                    "beta",
                    "cauchy",
                    "chisq",
                    "exp",
                    "f",
                    "gamma",
                    "logis",
                    "weibull"),
                default="norm")
            private$..transLog <- jmvcore::OptionBool$new(
                "transLog",
                transLog,
                default=FALSE)
            private$..standardize <- jmvcore::OptionBool$new(
                "standardize",
                standardize,
                default=FALSE)
            private$..refLine <- jmvcore::OptionBool$new(
                "refLine",
                refLine,
                default=TRUE)
            private$..band <- jmvcore::OptionBool$new(
                "band",
                band,
                default=FALSE)
            private$..methodQQ <- jmvcore::OptionList$new(
                "methodQQ",
                methodQQ,
                options=list(
                    "ell",
                    "pointwise",
                    "boot",
                    "ks",
                    "ts"),
                default="ell")
            private$..methodPP <- jmvcore::OptionList$new(
                "methodPP",
                methodPP,
                options=list(
                    "ell",
                    "boot"),
                default="ell")
            private$..detrend <- jmvcore::OptionBool$new(
                "detrend",
                detrend,
                default=FALSE)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "QQ",
                    "PP"),
                default="QQ")
            private$..refType <- jmvcore::OptionList$new(
                "refType",
                refType,
                options=list(
                    "qqline",
                    "identity"),
                default="identity")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..distrib)
            self$.addOption(private$..transLog)
            self$.addOption(private$..standardize)
            self$.addOption(private$..refLine)
            self$.addOption(private$..band)
            self$.addOption(private$..methodQQ)
            self$.addOption(private$..methodPP)
            self$.addOption(private$..detrend)
            self$.addOption(private$..type)
            self$.addOption(private$..refType)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        distrib = function() private$..distrib$value,
        transLog = function() private$..transLog$value,
        standardize = function() private$..standardize$value,
        refLine = function() private$..refLine$value,
        band = function() private$..band$value,
        methodQQ = function() private$..methodQQ$value,
        methodPP = function() private$..methodPP$value,
        detrend = function() private$..detrend$value,
        type = function() private$..type$value,
        refType = function() private$..refType$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..distrib = NA,
        ..transLog = NA,
        ..standardize = NA,
        ..refLine = NA,
        ..band = NA,
        ..methodQQ = NA,
        ..methodPP = NA,
        ..detrend = NA,
        ..type = NA,
        ..refType = NA,
        ..plotWidth = NA,
        ..plotHeight = NA)
)

qqplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotResults",
    inherit = jmvcore::Group,
    active = list(
        ErrorMessage = function() private$.items[["ErrorMessage"]],
        plot = function() private$.items[["plot"]],
        paramTable = function() private$.items[["paramTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Q-Q & P-P Plots",
                refs=list(
                    "qqplotr"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ErrorMessage",
                title="",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=400,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "dep",
                    "group",
                    "distrib",
                    "transLog",
                    "standardize",
                    "refLine",
                    "band",
                    "methodQQ",
                    "methodPP",
                    "detrend",
                    "type",
                    "refType",
                    "plotWidth",
                    "plotHeight")))
            self$add(jmvcore::Table$new(
                options=options,
                name="paramTable",
                title="Parameter Estimates",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"))))}))

qqplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "qqplot",
                version = c(1,0,0),
                options = options,
                results = qqplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Q-Q & P-P Plots
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param distrib .
#' @param transLog .
#' @param standardize .
#' @param refLine .
#' @param band .
#' @param methodQQ .
#' @param methodPP .
#' @param detrend .
#' @param type .
#' @param refType .
#' @param plotWidth .
#' @param plotHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ErrorMessage} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$paramTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$paramTable$asDF}
#'
#' \code{as.data.frame(results$paramTable)}
#'
#' @export
qqplot <- function(
    data,
    dep,
    group,
    distrib = "norm",
    transLog = FALSE,
    standardize = FALSE,
    refLine = TRUE,
    band = FALSE,
    methodQQ = "ell",
    methodPP = "ell",
    detrend = FALSE,
    type = "QQ",
    refType = "identity",
    plotWidth = 0,
    plotHeight = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("qqplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- qqplotOptions$new(
        dep = dep,
        group = group,
        distrib = distrib,
        transLog = transLog,
        standardize = standardize,
        refLine = refLine,
        band = band,
        methodQQ = methodQQ,
        methodPP = methodPP,
        detrend = detrend,
        type = type,
        refType = refType,
        plotWidth = plotWidth,
        plotHeight = plotHeight)

    analysis <- qqplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

