
# This file is automatically generated, you probably don't want to edit this

raincloudOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raincloudOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aVar = NULL,
            groupOne = NULL,
            groupTwo = NULL,
            nudgeBoxplot = FALSE,
            horizontal = FALSE,
            reverse = FALSE,
            colorPalette = "jmv",
            plotWidth = 0,
            plotHeight = 0,
            alphaC = 0.5, ...) {

            super$initialize(
                package="vijPlots",
                name="raincloud",
                requiresData=TRUE,
                ...)

            private$..aVar <- jmvcore::OptionVariable$new(
                "aVar",
                aVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..groupOne <- jmvcore::OptionVariable$new(
                "groupOne",
                groupOne,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..groupTwo <- jmvcore::OptionVariable$new(
                "groupTwo",
                groupTwo,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nudgeBoxplot <- jmvcore::OptionBool$new(
                "nudgeBoxplot",
                nudgeBoxplot,
                default=FALSE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..reverse <- jmvcore::OptionBool$new(
                "reverse",
                reverse,
                default=FALSE)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"),
                default="jmv")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..alphaC <- jmvcore::OptionNumber$new(
                "alphaC",
                alphaC,
                min=0,
                max=1,
                default=0.5)

            self$.addOption(private$..aVar)
            self$.addOption(private$..groupOne)
            self$.addOption(private$..groupTwo)
            self$.addOption(private$..nudgeBoxplot)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..reverse)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..alphaC)
        }),
    active = list(
        aVar = function() private$..aVar$value,
        groupOne = function() private$..groupOne$value,
        groupTwo = function() private$..groupTwo$value,
        nudgeBoxplot = function() private$..nudgeBoxplot$value,
        horizontal = function() private$..horizontal$value,
        reverse = function() private$..reverse$value,
        colorPalette = function() private$..colorPalette$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        alphaC = function() private$..alphaC$value),
    private = list(
        ..aVar = NA,
        ..groupOne = NA,
        ..groupTwo = NA,
        ..nudgeBoxplot = NA,
        ..horizontal = NA,
        ..reverse = NA,
        ..colorPalette = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..alphaC = NA)
)

raincloudResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raincloudResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Raincloud Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "aVar",
                    "groupOne",
                    "groupTwo",
                    "nudgeBoxplot",
                    "horizontal",
                    "reverse",
                    "colorPalette",
                    "alphaC",
                    "plotWidth",
                    "plotHeight")))}))

raincloudBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raincloudBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "raincloud",
                version = c(1,0,0),
                options = options,
                results = raincloudResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Raincloud Plot
#'
#' 
#' @param data .
#' @param aVar .
#' @param groupOne .
#' @param groupTwo .
#' @param nudgeBoxplot .
#' @param horizontal .
#' @param reverse .
#' @param colorPalette .
#' @param plotWidth .
#' @param plotHeight .
#' @param alphaC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
raincloud <- function(
    data,
    aVar,
    groupOne,
    groupTwo,
    nudgeBoxplot = FALSE,
    horizontal = FALSE,
    reverse = FALSE,
    colorPalette = "jmv",
    plotWidth = 0,
    plotHeight = 0,
    alphaC = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("raincloud requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aVar)) aVar <- jmvcore::resolveQuo(jmvcore::enquo(aVar))
    if ( ! missing(groupOne)) groupOne <- jmvcore::resolveQuo(jmvcore::enquo(groupOne))
    if ( ! missing(groupTwo)) groupTwo <- jmvcore::resolveQuo(jmvcore::enquo(groupTwo))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aVar), aVar, NULL),
            `if`( ! missing(groupOne), groupOne, NULL),
            `if`( ! missing(groupTwo), groupTwo, NULL))

    for (v in groupOne) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupTwo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- raincloudOptions$new(
        aVar = aVar,
        groupOne = groupOne,
        groupTwo = groupTwo,
        nudgeBoxplot = nudgeBoxplot,
        horizontal = horizontal,
        reverse = reverse,
        colorPalette = colorPalette,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        alphaC = alphaC)

    analysis <- raincloudClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

