
# This file is automatically generated, you probably don't want to edit this

scatterplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xaxis = NULL,
            yaxis = NULL,
            group = NULL,
            labelVar = NULL,
            ptSize = NULL,
            keepNA = FALSE,
            overlap = FALSE,
            plotBorder = FALSE,
            hline = FALSE,
            yinter = 0,
            vline = FALSE,
            xinter = 0,
            colorPalette = NULL, ...) {

            super$initialize(
                package="vijPlots",
                name="scatterplot",
                requiresData=TRUE,
                ...)

            private$..xaxis <- jmvcore::OptionVariable$new(
                "xaxis",
                xaxis,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..yaxis <- jmvcore::OptionVariable$new(
                "yaxis",
                yaxis,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal",
                    "id"))
            private$..ptSize <- jmvcore::OptionVariable$new(
                "ptSize",
                ptSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..keepNA <- jmvcore::OptionBool$new(
                "keepNA",
                keepNA,
                default=FALSE)
            private$..overlap <- jmvcore::OptionBool$new(
                "overlap",
                overlap,
                default=FALSE)
            private$..plotBorder <- jmvcore::OptionBool$new(
                "plotBorder",
                plotBorder,
                default=FALSE)
            private$..hline <- jmvcore::OptionBool$new(
                "hline",
                hline,
                default=FALSE)
            private$..yinter <- jmvcore::OptionNumber$new(
                "yinter",
                yinter,
                default=0)
            private$..vline <- jmvcore::OptionBool$new(
                "vline",
                vline,
                default=FALSE)
            private$..xinter <- jmvcore::OptionNumber$new(
                "xinter",
                xinter,
                default=0)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd"))

            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..group)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..ptSize)
            self$.addOption(private$..keepNA)
            self$.addOption(private$..overlap)
            self$.addOption(private$..plotBorder)
            self$.addOption(private$..hline)
            self$.addOption(private$..yinter)
            self$.addOption(private$..vline)
            self$.addOption(private$..xinter)
            self$.addOption(private$..colorPalette)
        }),
    active = list(
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        group = function() private$..group$value,
        labelVar = function() private$..labelVar$value,
        ptSize = function() private$..ptSize$value,
        keepNA = function() private$..keepNA$value,
        overlap = function() private$..overlap$value,
        plotBorder = function() private$..plotBorder$value,
        hline = function() private$..hline$value,
        yinter = function() private$..yinter$value,
        vline = function() private$..vline$value,
        xinter = function() private$..xinter$value,
        colorPalette = function() private$..colorPalette$value),
    private = list(
        ..xaxis = NA,
        ..yaxis = NA,
        ..group = NA,
        ..labelVar = NA,
        ..ptSize = NA,
        ..keepNA = NA,
        ..overlap = NA,
        ..plotBorder = NA,
        ..hline = NA,
        ..yinter = NA,
        ..vline = NA,
        ..xinter = NA,
        ..colorPalette = NA)
)

scatterplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatter Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=600,
                renderFun=".plot",
                clearWith=list(
                    "xaxis",
                    "yaxis",
                    "group",
                    "labelVar",
                    "ptSize",
                    "keepNA",
                    "overlap",
                    "plotBorder",
                    "hline",
                    "yinter",
                    "vline",
                    "xinter",
                    "colorPalette")))}))

scatterplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "scatterplot",
                version = c(1,0,0),
                options = options,
                results = scatterplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Scatter Plot
#'
#' 
#' @param data .
#' @param xaxis .
#' @param yaxis .
#' @param group .
#' @param labelVar .
#' @param ptSize .
#' @param keepNA .
#' @param overlap .
#' @param plotBorder .
#' @param hline .
#' @param yinter .
#' @param vline .
#' @param xinter .
#' @param colorPalette .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
scatterplot <- function(
    data,
    xaxis,
    yaxis,
    group,
    labelVar,
    ptSize,
    keepNA = FALSE,
    overlap = FALSE,
    plotBorder = FALSE,
    hline = FALSE,
    yinter = 0,
    vline = FALSE,
    xinter = 0,
    colorPalette) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scatterplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(xaxis)) xaxis <- jmvcore::resolveQuo(jmvcore::enquo(xaxis))
    if ( ! missing(yaxis)) yaxis <- jmvcore::resolveQuo(jmvcore::enquo(yaxis))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(ptSize)) ptSize <- jmvcore::resolveQuo(jmvcore::enquo(ptSize))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(xaxis), xaxis, NULL),
            `if`( ! missing(yaxis), yaxis, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(ptSize), ptSize, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scatterplotOptions$new(
        xaxis = xaxis,
        yaxis = yaxis,
        group = group,
        labelVar = labelVar,
        ptSize = ptSize,
        keepNA = keepNA,
        overlap = overlap,
        plotBorder = plotBorder,
        hline = hline,
        yinter = yinter,
        vline = vline,
        xinter = xinter,
        colorPalette = colorPalette)

    analysis <- scatterplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

